### ISSUE TITLE
Error when running rgbd_renderer.py

### ISSUE THREAD

**Issue by BenjaminBo** [ethnhe/raster_triangle#6]
Hello,
when running 
```python3 rgbd_renderer.py --cls ape --render_num 70000```I get the following Error:
```
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
cls:  ape
begin loading ape render set:
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "rgbd_renderer.py", line 252, in <module>
    main()
  File "rgbd_renderer.py", line 241, in main
    gen.gen_pack_zbuf_render()
  File "rgbd_renderer.py", line 173, in gen_pack_zbuf_render
    bg_pth = self.bg_img_pth_lst[randint(0, len_bg_lst-1)]
  File "/home/benjamin/.conda/envs/raster_triangle/lib/python3.6/random.py", line 221, in randint
    return self.randrange(a, b+1)
  File "/home/benjamin/.conda/envs/raster_triangle/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,0, 0)
```

**Comment by BenjaminBo** [comment]
Solved by using the SUN2012 dataset properly
